package control

var feishuCommandSpecsSettings = []feishuCommandSpec{
	{
		definition: FeishuCommandDefinition{
			ID:               FeishuCommandReasoning,
			GroupID:          FeishuCommandGroupSendSettings,
			Title:            "推理强度",
			CanonicalSlash:   "/reasoning",
			CanonicalMenuKey: "reasoning",
			ArgumentKind:     FeishuCommandArgumentChoice,
			ArgumentFormHint: "high",
			ArgumentFormNote: "输入 low / medium / high / xhigh / clear。",
			ArgumentSubmit:   "应用",
			Description:      "查看当前推理强度；bare `/reasoning` 会返回可选参数卡片。",
			Examples:         []string{"/reasoning high", "/reasoning clear"},
			Options: []FeishuCommandOption{
				commandOption("/reasoning", "reasoning", "low", "low", "把后续飞书消息切到 low 推理，直到 clear 或接管清理。"),
				commandOption("/reasoning", "reasoning", "medium", "medium", "把后续飞书消息切到 medium 推理，直到 clear 或接管清理。"),
				commandOption("/reasoning", "reasoning", "high", "high", "把后续飞书消息切到 high 推理，直到 clear 或接管清理。"),
				commandOption("/reasoning", "reasoning", "xhigh", "xhigh", "把后续飞书消息切到 xhigh 推理，直到 clear 或接管清理。"),
				commandOption("/reasoning", "reasoning", "clear", "clear", "清除飞书临时推理强度覆盖。"),
			},
			ShowInHelp: true,
			ShowInMenu: true,
			RecommendedMenu: &FeishuRecommendedMenu{
				Key:         "reasoning",
				Name:        "推理强度",
				Description: "打开推理强度参数卡；如果知道完整 key，也可直接使用 `reasoning_high` 这类直达入口。",
			},
		},
		textPrefixes: []feishuCommandPrefixMatch{
			{alias: "/reasoning", kind: ActionReasoningCommand},
			{alias: "/effort", kind: ActionReasoningCommand},
		},
		menuExact: []feishuCommandMatch{
			{alias: "reasoning", action: Action{Kind: ActionReasoningCommand, Text: "/reasoning"}},
			{alias: "reasonlow", action: Action{Kind: ActionReasoningCommand, Text: "/reasoning low"}},
			{alias: "reasonmedium", action: Action{Kind: ActionReasoningCommand, Text: "/reasoning medium"}},
			{alias: "reasonhigh", action: Action{Kind: ActionReasoningCommand, Text: "/reasoning high"}},
			{alias: "reasonxhigh", action: Action{Kind: ActionReasoningCommand, Text: "/reasoning xhigh"}},
			{alias: "reasonmax", action: Action{Kind: ActionReasoningCommand, Text: "/reasoning max"}},
		},
		menuDynamic: []feishuCommandDynamicMenuMatch{
			{prefix: "reasoning_", kind: ActionReasoningCommand, parseArgument: normalizeReasoningMenuArgument},
			{prefix: "reasoning-", kind: ActionReasoningCommand, parseArgument: normalizeReasoningMenuArgument},
			{prefix: "reason_", kind: ActionReasoningCommand, parseArgument: normalizeReasoningMenuArgument},
			{prefix: "reason-", kind: ActionReasoningCommand, parseArgument: normalizeReasoningMenuArgument},
		},
	},
	{
		definition: FeishuCommandDefinition{
			ID:               FeishuCommandModel,
			GroupID:          FeishuCommandGroupSendSettings,
			Title:            "模型与推理强度",
			CanonicalSlash:   "/model",
			CanonicalMenuKey: "model",
			ArgumentKind:     FeishuCommandArgumentText,
			ArgumentFormHint: "gpt-5.5 high",
			ArgumentFormNote: "输入模型名，或输入“模型名 推理强度”。",
			ArgumentSubmit:   "应用",
			Description:      "查看当前模型与推理强度；bare `/model` 可一起选择并应用。",
			Examples:         []string{"/model gpt-5.5", "/model gpt-5.5 high", "/model clear"},
			ShowInHelp:       true,
			ShowInMenu:       true,
			RecommendedMenu: &FeishuRecommendedMenu{
				Key:         "model",
				Name:        "模型与推理强度",
				Description: "打开模型与推理强度卡片；如果知道完整模型 key，也可直接使用 `model_gpt-5.5` 这类直达入口。",
			},
		},
		textPrefixes: []feishuCommandPrefixMatch{
			{alias: "/model", kind: ActionModelCommand},
		},
		menuExact: []feishuCommandMatch{
			{alias: "model", action: Action{Kind: ActionModelCommand, Text: "/model"}},
		},
		menuDynamic: []feishuCommandDynamicMenuMatch{
			{prefix: "model_", kind: ActionModelCommand, parseArgument: normalizeModelMenuArgument},
			{prefix: "model-", kind: ActionModelCommand, parseArgument: normalizeModelMenuArgument},
		},
	},
	{
		definition: FeishuCommandDefinition{
			ID:               FeishuCommandAccess,
			GroupID:          FeishuCommandGroupSendSettings,
			Title:            "执行权限",
			CanonicalSlash:   "/permission",
			CanonicalMenuKey: "access",
			ArgumentKind:     FeishuCommandArgumentChoice,
			ArgumentFormHint: "confirm",
			ArgumentFormNote: "输入 full / confirm / clear。",
			ArgumentSubmit:   "应用",
			Description:      "查看当前执行权限；bare `/permission` 会返回可选参数卡片。",
			Examples:         []string{"/permission confirm", "/permission clear"},
			Options: []FeishuCommandOption{
				commandOption("/permission", "access", "full", "full", "把后续飞书消息切到 full 权限，直到 clear 或接管清理。"),
				commandOption("/permission", "access", "confirm", "confirm", "把后续飞书消息切到 confirm 权限，直到 clear 或接管清理。"),
				commandOption("/permission", "access", "clear", "clear", "恢复飞书默认执行权限。"),
			},
			ShowInHelp: true,
			ShowInMenu: true,
			RecommendedMenu: &FeishuRecommendedMenu{
				Key:         "access",
				Name:        "执行权限",
				Description: "打开执行权限参数卡；如果知道完整 key，也可直接使用 `access_confirm` 这类直达入口。",
			},
		},
		textPrefixes: []feishuCommandPrefixMatch{
			{alias: "/permission", kind: ActionAccessCommand},
			{alias: "/permissions", kind: ActionAccessCommand},
			{alias: "/access", kind: ActionAccessCommand},
			{alias: "/approval", kind: ActionAccessCommand},
		},
		menuExact: []feishuCommandMatch{
			{alias: "access", action: Action{Kind: ActionAccessCommand, Text: "/permission"}},
			{alias: "approval", action: Action{Kind: ActionAccessCommand, Text: "/permission"}},
			{alias: "accessfull", action: Action{Kind: ActionAccessCommand, Text: "/permission full"}},
			{alias: "approvalfull", action: Action{Kind: ActionAccessCommand, Text: "/permission full"}},
			{alias: "accessconfirm", action: Action{Kind: ActionAccessCommand, Text: "/permission confirm"}},
			{alias: "approvalconfirm", action: Action{Kind: ActionAccessCommand, Text: "/permission confirm"}},
		},
		menuDynamic: []feishuCommandDynamicMenuMatch{
			{prefix: "access_", kind: ActionAccessCommand, parseArgument: normalizeAccessMenuArgument},
			{prefix: "access-", kind: ActionAccessCommand, parseArgument: normalizeAccessMenuArgument},
			{prefix: "approval_", kind: ActionAccessCommand, parseArgument: normalizeAccessMenuArgument},
			{prefix: "approval-", kind: ActionAccessCommand, parseArgument: normalizeAccessMenuArgument},
		},
	},
	{
		definition: FeishuCommandDefinition{
			ID:               FeishuCommandPlan,
			GroupID:          FeishuCommandGroupSendSettings,
			Title:            "Plan 模式",
			CanonicalSlash:   "/plan",
			CanonicalMenuKey: "plan",
			ArgumentKind:     FeishuCommandArgumentChoice,
			ArgumentFormHint: "on",
			ArgumentFormNote: "输入 on / off。",
			ArgumentSubmit:   "应用",
			Description:      "控制后续新 turn 是否按 upstream Plan mode 启动；bare `/plan` 会返回可选参数卡片。",
			Examples:         []string{"/plan on", "/plan off"},
			Options: []FeishuCommandOption{
				commandOption("/plan", "plan", "on", "开启", "后续新 turn 按 Plan mode 启动。"),
				commandOption("/plan", "plan", "off", "关闭", "后续新 turn 按默认执行模式启动。"),
			},
			ShowInHelp: true,
			ShowInMenu: true,
			RecommendedMenu: &FeishuRecommendedMenu{
				Key:         "plan",
				Name:        "Plan 模式",
				Description: "打开 Plan 模式参数卡，切换后续新 turn 是否启用 Plan 模式。",
			},
		},
		textPrefixes: []feishuCommandPrefixMatch{
			{alias: "/plan", kind: ActionPlanCommand},
		},
		menuExact: []feishuCommandMatch{
			{alias: "plan", action: Action{Kind: ActionPlanCommand, Text: "/plan"}},
		},
		menuDynamic: []feishuCommandDynamicMenuMatch{
			{prefix: "plan_", kind: ActionPlanCommand, parseArgument: normalizePlanMenuArgument},
			{prefix: "plan-", kind: ActionPlanCommand, parseArgument: normalizePlanMenuArgument},
		},
	},
	{
		definition: FeishuCommandDefinition{
			ID:               FeishuCommandVerbose,
			GroupID:          FeishuCommandGroupSendSettings,
			Title:            "提示详细程度",
			CanonicalSlash:   "/verbose",
			CanonicalMenuKey: "verbose",
			ArgumentKind:     FeishuCommandArgumentChoice,
			ArgumentFormHint: "normal",
			ArgumentFormNote: "输入 quiet / normal / verbose / chatty。",
			ArgumentSubmit:   "应用",
			Description:      "控制飞书前端显示过程消息的详细程度；bare `/verbose` 会返回可选档位卡片。",
			Examples:         []string{"/verbose quiet", "/verbose normal", "/verbose verbose", "/verbose chatty"},
			Options: []FeishuCommandOption{
				commandOption("/verbose", "verbose", "quiet", "quiet", "只显示最终答复和必须可见的交互提示。"),
				commandOption("/verbose", "verbose", "normal", "normal", "显示 plan、最终答复，以及会影响当前状态的共享过程项，例如文件修改、上下文压缩、MCP 调用。"),
				commandOption("/verbose", "verbose", "verbose", "verbose", "显示完整共享过程卡；卡片末行显示最新的真实 reasoning / thinking 摘要，不保留推理历史。"),
				commandOption("/verbose", "verbose", "chatty", "chatty", "在 verbose 基础上按工具分段保留完整 reasoning / thinking 历史。"),
			},
			ShowInHelp: true,
			ShowInMenu: true,
		},
		textPrefixes: []feishuCommandPrefixMatch{
			{alias: "/verbose", kind: ActionVerboseCommand},
		},
		menuExact: []feishuCommandMatch{
			{alias: "verbose", action: Action{Kind: ActionVerboseCommand, Text: "/verbose"}},
		},
		menuDynamic: []feishuCommandDynamicMenuMatch{
			{prefix: "verbose_", kind: ActionVerboseCommand, parseArgument: normalizeVerboseMenuArgument},
			{prefix: "verbose-", kind: ActionVerboseCommand, parseArgument: normalizeVerboseMenuArgument},
		},
	},
	{
		definition: FeishuCommandDefinition{
			ID:               FeishuCommandCodexProfile,
			GroupID:          FeishuCommandGroupSendSettings,
			Title:            "切换 Codex Profile",
			CanonicalSlash:   "/codexprofile",
			CanonicalMenuKey: "codex_profile",
			ArgumentKind:     FeishuCommandArgumentText,
			ArgumentFormHint: "native",
			ArgumentSubmit:   "切换",
			Description:      "查看当前 Codex Profile；bare `/codexprofile` 会返回可切换的 Profile 下拉卡片。",
			Examples:         []string{"/codexprofile native"},
			ShowInHelp:       true,
			ShowInMenu:       true,
		},
		textPrefixes: []feishuCommandPrefixMatch{
			{alias: "/codexprofile", kind: ActionCodexProfileCommand},
		},
		menuExact: []feishuCommandMatch{
			{alias: "codex_profile", action: Action{Kind: ActionCodexProfileCommand, Text: "/codexprofile"}},
		},
	},
	{
		definition: FeishuCommandDefinition{
			ID:               FeishuCommandClaudeProfile,
			GroupID:          FeishuCommandGroupSendSettings,
			Title:            "切换 Claude 配置",
			CanonicalSlash:   "/claudeprofile",
			CanonicalMenuKey: "claude_profile",
			ArgumentKind:     FeishuCommandArgumentText,
			ArgumentFormHint: "default",
			ArgumentFormNote: "输入已存在的 Claude 配置 ID。",
			ArgumentSubmit:   "切换",
			Description:      "查看当前 Claude 配置；bare `/claudeprofile` 会返回可切换的配置下拉卡片。",
			Examples:         []string{"/claudeprofile default"},
			ShowInHelp:       true,
			ShowInMenu:       true,
		},
		textPrefixes: []feishuCommandPrefixMatch{
			{alias: "/claudeprofile", kind: ActionClaudeProfileCommand},
		},
		menuExact: []feishuCommandMatch{
			{alias: "claude_profile", action: Action{Kind: ActionClaudeProfileCommand, Text: "/claudeprofile"}},
		},
	},
	goalCommandSpec(),
	openCodeProfileCommandSpec(),
}
