// Code generated by scripts/shim/prepare-shim-embed.sh; DO NOT EDIT.

//go:build darwin && amd64

package embed

import _ "embed"

//go:embed assets/codex-feishu-relay-shim-darwin-amd64.zst
var embeddedShim_darwin_amd64 []byte

func init() {
	register(Asset{
		SourceDigest: "b9fcfee9a6ec7770920c2d5fa5759143bffc182504044210fc392e055378fcdd",
		SHA256:       "4c119f53385218ec11e3ab0af90ff72b5abdf8c565d55306a9cce13991bdf79a",
		Zstd:         embeddedShim_darwin_amd64,
	})
}
