// Code generated by scripts/shim/prepare-shim-embed.sh; DO NOT EDIT.

//go:build linux && arm64

package embed

import _ "embed"

//go:embed assets/codex-feishu-relay-shim-linux-arm64.zst
var embeddedShim_linux_arm64 []byte

func init() {
	register(Asset{
		SourceDigest: "c566da28e34a6c994e5712f1dd6b044a084510488454ab3a8d94419834e111c9",
		SHA256:       "71a64004d156240ea7badc9a56d386f46a25b3228e80f49d80250527361829f8",
		Zstd:         embeddedShim_linux_arm64,
	})
}
