// Code generated by scripts/shim/prepare-shim-embed.sh; DO NOT EDIT.

//go:build darwin && arm64

package embed

import _ "embed"

//go:embed assets/codex-feishu-relay-shim-darwin-arm64.zst
var embeddedShim_darwin_arm64 []byte

func init() {
	register(Asset{
		SourceDigest: "c566da28e34a6c994e5712f1dd6b044a084510488454ab3a8d94419834e111c9",
		SHA256:       "c94ca28be1e2ff47b40a249fa2e6effa7a6dd227606ab83ebfa7beb81647b3c0",
		Zstd:         embeddedShim_darwin_arm64,
	})
}
