// Code generated by scripts/shim/prepare-shim-embed.sh; DO NOT EDIT.

//go:build windows && amd64

package embed

import _ "embed"

//go:embed assets/codex-feishu-relay-shim-windows-amd64.zst
var embeddedShim_windows_amd64 []byte

func init() {
	register(Asset{
		SourceDigest: "c566da28e34a6c994e5712f1dd6b044a084510488454ab3a8d94419834e111c9",
		SHA256:       "1a97e6c55d502f8b9d2a1006c6d8876619135eff731d2c4c4475fc44c6bc6ffb",
		Zstd:         embeddedShim_windows_amd64,
	})
}
