// Code generated by scripts/shim/prepare-shim-embed.sh; DO NOT EDIT.

//go:build linux && amd64

package embed

import _ "embed"

//go:embed assets/codex-feishu-relay-shim-linux-amd64.zst
var embeddedShim_linux_amd64 []byte

func init() {
	register(Asset{
		SourceDigest: "c566da28e34a6c994e5712f1dd6b044a084510488454ab3a8d94419834e111c9",
		SHA256:       "d860228cfc3b0682f4c82c4c0eb3d77e2d80744756c28f0dbd317fc66f325817",
		Zstd:         embeddedShim_linux_amd64,
	})
}
